package com.test.bean;

import lombok.Data;

import java.util.List;

@Data
public class Bean1 {
    private long id;
    private String name;
    private int age;
    private List<Integer> list;
    private List<Integer>[] list2;
    private String field1;
    private String field2;
    private String field3;
    private String field4;
    private String field5;
    private String field6;
    private String field7;
    private String field8;
    private String field9;
    private String field10;
    private String field11;
    private String field12;
    private String field13;
    private String field14;
    private String field15;
    private String field16;
    private String field17;
    private String field18;
    private String field19;
    private String field20;
    private String field21;
    private String field22;
    private String field23;
    private String field24;
    private String field25;
    private String field26;
    private String field27;
    private String field28;
    private String field29;
    private String field30;
    private String field31;
    private String field32;
    private String field33;
    private String field34;
    private String field35;
    private String field36;
    private String field37;
    private String field38;
    private String field39;
    private String field40;
    private String field41;
    private String field42;
    private String field43;
    private String field44;
    private String field45;
    private String field46;
    private String field47;
    private String field48;
    private String field49;
    private String field50;
    private String field51;
    private String field52;
    private String field53;
    private String field54;
    private String field55;
    private String field56;
    private String field57;
    private String field58;
    private String field59;
    private String field60;
    private String field61;
    private String field62;
    private String field63;
    private String field64;
    private String field65;
    private String field66;
    private String field67;
    private String field68;
    private String field69;
    private String field70;
    private String field71;
    private String field72;
    private String field73;
    private String field74;
    private String field75;
    private String field76;
    private String field77;
    private String field78;
    private String field79;
    private String field80;
    private String field81;
    private String field82;
    private String field83;
    private String field84;
    private String field85;
    private String field86;
    private String field87;
    private String field88;
    private String field89;
    private String field90;
    private String field91;
    private String field92;
    private String field93;
    private String field94;
    private String field95;
    private String field96;
    private String field97;
    private String field98;
    private String field99;
    private String field100;
    private int int1 = 1;
    private int int2 = 2;
    private int int3 = 3;
    private int int4 = 4;
    private int int5 = 5;
    private int int6 = 6;
    private int int7 = 7;
    private int int8 = 8;
    private int int9 = 9;
    private int int10 = 10;
    private int int11 = 11;
    private int int12 = 12;
    private int int13 = 13;
    private int int14 = 14;
    private int int15 = 15;
    private int int16 = 16;
    private int int17 = 17;
    private int int18 = 18;
    private int int19 = 19;
    private int int20 = 20;
    private int int21 = 21;
    private int int22 = 22;
    private int int23 = 23;
    private int int24 = 24;
    private int int25 = 25;
    private int int26 = 26;
    private int int27 = 27;
    private int int28 = 28;
    private int int29 = 29;
    private int int30 = 30;
    private int int31 = 31;
    private int int32 = 32;
    private int int33 = 33;
    private int int34 = 34;
    private int int35 = 35;
    private int int36 = 36;
    private int int37 = 37;
    private int int38 = 38;
    private int int39 = 39;
    private int int40 = 40;
    private int int41 = 41;
    private int int42 = 42;
    private int int43 = 43;
    private int int44 = 44;
    private int int45 = 45;
    private int int46 = 46;
    private int int47 = 47;
    private int int48 = 48;
    private int int49 = 49;
    private int int50 = 50;
    private int int51 = 51;
    private int int52 = 52;
    private int int53 = 53;
    private int int54 = 54;
    private int int55 = 55;
    private int int56 = 56;
    private int int57 = 57;
    private int int58 = 58;
    private int int59 = 59;
    private int int60 = 60;
    private int int61 = 61;
    private int int62 = 62;
    private int int63 = 63;
    private int int64 = 64;
    private int int65 = 65;
    private int int66 = 66;
    private int int67 = 67;
    private int int68 = 68;
    private int int69 = 69;
    private int int70 = 70;
    private int int71 = 71;
    private int int72 = 72;
    private int int73 = 73;
    private int int74 = 74;
    private int int75 = 75;
    private int int76 = 76;
    private int int77 = 77;
    private int int78 = 78;
    private int int79 = 79;
    private int int80 = 80;
    private int int81 = 81;
    private int int82 = 82;
    private int int83 = 83;
    private int int84 = 84;
    private int int85 = 85;
    private int int86 = 86;
    private int int87 = 87;
    private int int88 = 88;
    private int int89 = 89;
    private int int90 = 90;
    private int int91 = 91;
    private int int92 = 92;
    private int int93 = 93;
    private int int94 = 94;
    private int int95 = 95;
    private int int96 = 96;
    private int int97 = 97;
    private int int98 = 98;
    private int int99 = 99;
    private int int100 = 100;

}